### ISSUE TITLE
Broken demo on mobile

### ISSUE THREAD

**Issue by tonygriv** [hanford/react-drag-drawer#14]
I think that drawer is not working properly on mobile devices on demo page. Maybe it's not working properly at all.

**Comment by hanford** [comment]
Definitely the demo page, pointing to a bad deployment, I’ll update that now

**Comment by hanford** [comment]
Thanks for pointing out, has since been resolved! We're using it heavily in production on [eaze](https://eaze.com)

**Comment by tonygriv** [comment]
Ok, thanks for response :)

**Comment by tonygriv** [comment]
@hanford, could you publish final version to npm? It seems to be broken in npm too.

**Comment by hanford** [comment]
@tonygriv can you give me a working reproduction case in [stackblitz](https://stackblitz.com) or [code sandbox](https://codesandbox.io) ?? We're using it in production on [Eaze](https://eaze.com), and I'm also using it on my [personal website](https://jackhanford.com/) when you click "Contact me" .. you can see the code I have [over here](https://github.com/hanford/personal-website/blob/master/components/social-modal.js)
