### ISSUE TITLE
Target container is not a DOM element 

### ISSUE THREAD

**Issue by dsmalicsi** [hanford/react-drag-drawer#17]
Hi, I have built a mobile app that uses this package. However, when testing it on Android (not yet tested on iOS), I have a button that toggles the state to open/close the drawer 
`this.setState({ drawerOpen: !drawerOpen })`

This works well on desktop browsers and mobile browsers. But when it is built in cordova as an Android APK, then trying to open the drawer, I get the following error message:

> a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:10166 Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
>     at o (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:6175)
>     at p (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:6365)
>     at Gs (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:11344)
>     at t.e [as render] (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:60621)
>     at Ui (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:9702)
>     at Yi (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:9942)
>     at ka (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:10556)
>     at Oa (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:10577)
>     at ss (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:10829)
>     at os (a74475dc70c75cc9e201d1a682b0c4c6dc0425a0.js?meteor_js_resource=true:formatted:10788)

Line 60621 points to this piece of code:
`    return (0, y.createPortal)(u.default.createElement(l.Motion, {`

Which I assume is related to `react-motion` or probably on the `isClientSide()` helper? I hope these makes sense and would love to know if it can be fixed.

**Comment by dsmalicsi** [comment]
Nevermind, I fixed it. I had to specify a `parentElement` prop, and I set it to `document.body`

**Comment by hanford** [comment]
Cool, haven’t tried using the package with Cordova 😅
