### ISSUE TITLE
Scroll content on mobile closes drawer

### ISSUE THREAD

**Issue by dsmalicsi** [hanford/react-drag-drawer#18]
Hi, I found this weird behaviour on mobile when the content height is larger than the drawer.
Swiping up in the drawer will scroll the content just as usual. 
But when you're at the bottom part of the content and release your finger, trying to go back up by swiping down acts as if you're dragging the whole drawer and it eventually closes itself, so there's no way to scroll back again to see the content above.
I hope I explained it well, looking forward for a fix. Thanks!

**Comment by hanford** [comment]
can you share an environment where there is occuring? either a repo or an environment on `https://stackblitz.com/` would be ideal

**Comment by dsmalicsi** [comment]
Hi @hanford I'm not comfortable in sharing the project publicly. Can I send you the link to the testing environment via email instead?

**Comment by hanford** [comment]
@dsmalicsi please don't share any private information!

I'm asking you to create a new repo, or get the bare minimum code somewhere that i can see to reproduce the bug.

Here is an environment that already has the [react-drag-drawer demo](https://stackblitz.com/edit/react-j6ez7z?file=index.js) up and running. Change any code you need to to clearly show the bug.

Let me know if you have any additional questions!

**Comment by hanford** [comment]
Going to go ahead and close this issue. Feel free to open if you run into something else!

**Comment by lchandramohan** [comment]
Below issue is happening for me.

I am using in reactjs app using in webview(Hybrid App). Scrolling up is working fine but when i scrolling down, drawer is closing in mobile. 

Please help me to resolve this issue.
