### ISSUE TITLE
Triggers reloading on Android

### ISSUE THREAD

**Issue by jcquinlan** [hanford/react-drag-drawer#2]
The dragging down motion is the same one used to refresh a page on mobile. Closing the drawer by dragging also refreshes the page.

**Comment by hanford** [comment]
Interesting, I'm an iOS user unfortunately .. @jcquinlan ..

Are you aware of anyway to cancel that event from happening?

Does this look adequate? http://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature

**Comment by langpavel** [comment]
Looks like this is the one

**Comment by hanford** [comment]
Fix is live in `0.5.0`

**Comment by langpavel** [comment]
It still trigger reload in Chrome on real Android :-\

**Comment by hanford** [comment]
Demo is not updated @langpavel , I'm using a chrome pixel at work and testing it works. I'll update the demo tho

**Comment by hanford** [comment]
@langpavel demo is updated!

**Comment by langpavel** [comment]
Works like a charm! Thanks! :+1:
