### ISSUE TITLE
Fix typo in Proptypes

### ISSUE THREAD

**Issue by DariaShymanGymondo** [hanford/react-drag-drawer#28]
Tests are failing because Proptypes is not defined.
Please update the line 40: 
`containerOpacity: Proptypes.number,`
to 
`containerOpacity: PropTypes.number,`

**Comment by Marten002** [comment]
I have the same problem of `containerOpacity: Proptypes.number,`

**Comment by hanford** [comment]
thanks, fix is live in v3.3.3
