### ISSUE TITLE
Stuttering toggle animation when using `direction='left'` props.

### ISSUE THREAD

**Issue by zaki-binary** [hanford/react-drag-drawer#32]
Drawer has a stuttering animation when using `direction='left` props, other directions or alignments don't seem to have this issue. It's visible in the demo example as well.

**Comment by hanford** [comment]
I noticed that as well, I'm not using this library a ton anymore but would love a PR if you or someone else get's to the bottom of it.

It's especially weird, because it doesn't happen with `direction="right"`

**Comment by zaki-binary** [comment]
Hey man, I've submitted the PR here #33  , after brief investigation it seems like the transforms didn't play nicely with the spring effect from `react-motion`.

**Comment by hanford** [comment]
@zaki-binary ahh, should I revert?

**Comment by zaki-hanafiah** [comment]
@hanford , nope. I simply closed the issue since the PR is merged, were there any regression or issues caused by it?
